---
# tasks file for samba (join existing domain)

- name: Join existing domain as a Domain Controller
  command: samba-tool domain join {{ samba_realm }} DC \
           --username=administrator \
           --realm={{ samba_realm|upper }} \
           --password={{ samba_admin_pass }} \
           --workgroup={{ samba_domain|upper }} \
           --dns-backend=SAMBA_INTERNAL
  args:
    creates: /var/lib/samba/private/sam.ldb
  tags: samba
