---
# tasks file for samba

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: samba

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: samba

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: samba

- name: Check for sample configuration file
  command: grep 'Sample configuration file' /etc/samba/smb.conf
  ignore_errors: yes
  changed_when: False
  register: smb_conf
  tags: samba

- name: Remove sample configuration file
  file: path=/etc/samba/smb.conf state=absent
  when: smb_conf.rc == 0
  tags: samba

- include: provision.yml
  when: samba_create_domain
  tags: samba

- include: join.yml
  when: not samba_create_domain
  tags: samba

- name: Ensure Samba service is started and enabled on boot
  service: name={{ samba_service }} state=started enabled=yes
  tags: samba
