---
# tasks file for samba (provision new domain)

- name: Provision domain controller
  command: samba-tool domain provision \
           --realm={{ samba_realm|upper }} \
           --domain={{ samba_domain|upper }} \
           --adminpass={{ samba_admin_pass }} \
           --dns-backend=SAMBA_INTERNAL \
           --option='dns forwarder'={{ samba_dns_forwarder }} \
           --quiet \
           --server-role=dc \
           --use-xattrs=yes \
           --use-rfc2307
  args:
    creates: /var/lib/samba/private/sam.ldb
  tags: samba

- name: Create Samba configuration file
  template: >
    src=smb.conf.j2
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    mode=0644
  notify: restart samba
  tags: samba
