---
# tasks file for samba (Ubuntu specific)

- name: Install Samba packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: samba_packages
  tags: samba

- name: Ensure smbd service is disabled
  service: name=smbd state=stopped enabled=no
  tags: samba
